export const L = {
  inboxSection: "Inbox",
  memoriesSection: "Memories",
  skillsSection: "Skills",
  mcpSection: "MCP Servers",
  schedulesSection: "Schedules",
  webhooksSection: "Webhooks",
  automationsSection: "Automations",
  pluginsSection: "Plugins",
  settingsSection: "Settings",
  settingsCategoriesLabel: "Settings categories",
  settingsGeneralCategory: "General",
  settingsProvidersCategory: "Providers",
  settingsFilesCategory: "Files",
  settingsConnectionCategory: "Connection",
  providerNavigationLabel: "Provider settings",
  providerOverview: "Overview",

  appearanceTitle: "Appearance",
  themeLabel: "Theme",
  themeHint: "Choose a light or dark interface, or follow your system setting.",
  themeLight: "Light",
  themeDark: "Dark",
  themeSystem: "System",

  personaTitle: "Persona",
  personaLabel: "Custom instructions",
  personaHint: "Added to the assistant's system prompt in every conversation. The base personality stays intact — this only adds to it.",
  personaPlaceholder: "e.g. Always reply in a concise, friendly tone and prefer metric units.",
  personaSaved: "Saved",
  personaSaving: "Saving…",

  featuresTitle: "Features",
  enableMemoriesLabel: "Memories",
  enableMemoriesHint: "A durable notes pool the assistant reads and updates across conversations. Adds a Memories button to the rail.",
  enableAutomationsLabel: "Automations",
  enableAutomationsHint: "Scheduled and event-driven runs (cron, webhooks). Adds an Automations button to the rail.",
  notificationsTitle: "Notifications",
  notifyOnRunCompletionLabel: "Run finished",
  notifyOnRunCompletionHint: "Show a system notification when an agent run finishes, fails, or times out.",
  notifyOnActionRequiredLabel: "Action required",
  notifyOnActionRequiredHint: "Show a system notification when a conversation is waiting for your input.",

  providersTitle: "Inference providers",
  defaultModelLabel: "Default model",
  defaultModelHint: "The model new conversations use unless one is picked in the composer.",
  defaultModelServerFallback: "Automatic (recommended)",
  providerConfiguredBadge: "Configured",
  providerAvailableBadge: "Available",
  providerUnavailableBadge: "Unavailable",
  providerNotConfiguredBadge: "Not configured",
  providerNeedsAttentionBadge: "Needs attention",
  providerEnvBadge: "From environment",
  providerEnvNote: "This provider resolves its credentials from the ambient environment — no configuration needed.",
  secretRefHint: "Enter the name of an environment variable holding this secret, referenced as ${MY_VAR}. The value is never stored — only the reference.",
  secretKeychainHint: "Stored encrypted in your OS keychain by the desktop app. Only a generated reference is sent over HTTP or saved.",
  secretRefPlaceholder: "${MY_API_KEY}",
  secretStoredPlaceholder: "•••••••• (stored — leave blank to keep)",
  secretUnavailablePlaceholder: "Enter this credential again",
  secretUnavailableHint: "The saved credential cannot be read by this app. Enter it again and save.",
  secretEnvUnavailablePlaceholder: "Server environment variable unavailable",
  secretEnvUnavailableHint: "The saved environment reference is not available to the server. Configure it in the server environment, then restart or retry.",
  modelCatalogRetry: "Retry",
  modelCatalogRetrying: "Retrying…",
  modelCatalogStaleBadge: "Last known",
  modelCatalogEmpty: "No models were returned.",
  modelCatalogSavedOnly: "(saved selection)",
  providerSave: "Save",
  providerSaving: "Saving…",
  providerRemove: "Remove",

  skill: "Skill",
  skills: "Skills",
  mcpServer: "MCP server",
  mcpServers: "MCP servers",
  memory: "Memory",
  memories: "Memories",
  schedule: "Schedule",
  schedules: "Schedules",
  webhook: "Webhook",
  webhooks: "Webhooks",
  run: "Run",

  cronSchedule: "Scheduled",
  webhookSchedule: "Webhook",

  builtInBadge: "Built-in",
  customBadge: "Custom",
  pluginBadge: "Plugin",
  customizedBadge: "Customized",
  hasScheduleTitle: "Has a schedule",
  manageSchedules: "Manage in Schedules →",

  noSkills: "No skills yet",
  noMcpServers: "No MCP servers yet",
  noMemories: "No memories yet",
  noSchedules: "No schedules yet",
  noWebhooks: "No webhooks yet",
  noPlugins: "No plugins installed",
} as const;

export function scheduleKindLabel(kind: "cron" | "webhook"): string {
  return kind === "cron" ? L.cronSchedule : L.webhookSchedule;
}
